In [ ]:
#
# hw4pr1iris_modeler:  iris clasification via nearest neighbors
#

In [ ]:
#
# (now, to explore how we _can_ use data to do better... :-) 
#

In [1]:
# libraries!
import numpy as np      # numpy is Python's "array" library
import pandas as pd     # Pandas is Python's "data" library ("dataframe" == spreadsheet)

In [2]:
# let's read in our flower data...
# 
# for read_csv, use header=0 when row 0 is a header row
# 
cleaned_filename = "iris_cleaned.csv"
df_tidy = pd.read_csv(cleaned_filename)   # encoding="utf-8" et al.
print(f"{cleaned_filename} : file read into a pandas dataframe.")
df_tidy

iris_cleaned.csv : file read into a pandas dataframe.


sepallen  sepalwid  petallen  petalwid   irisname  irisnum
0         4.6       3.6       1.0       0.2     setosa        0
1         4.3       3.0       1.1       0.1     setosa        0
2         5.0       3.2       1.2       0.2     setosa        0
3         5.8       4.0       1.2       0.2     setosa        0
4         4.4       3.0       1.3       0.2     setosa        0
5         4.4       3.2       1.3       0.2     setosa        0
6         4.5       2.3       1.3       0.3     setosa        0
7         4.7       3.2       1.3       0.2     setosa        0
8         5.0       3.5       1.3       0.3     setosa        0
9         5.4       3.9       1.3       0.4     setosa        0
10        5.5       3.5       1.3       0.2     setosa        0
11        4.4       2.9       1.4       0.2     setosa        0
12        4.6       3.4       1.4       0.3     setosa        0
13        4.6       3.2       1.4       0.2     setosa        0
14        4.8       3.0       1.4       0.1     setosa        0
15        4.8       3.0       1.4       0.3     setosa        0
16        4.9       3.0       1.4       0.2     setosa        0
17        5.0       3.6       1.4       0.2     setosa        0
18        5.0       3.3       1.4       0.2     setosa        0
19        5.1       3.5       1.4       0.2     setosa        0
20        5.1       3.5       1.4       0.3     setosa        0
21        5.2       3.4       1.4       0.2     setosa        0
22        5.5       4.2       1.4       0.2     setosa        0
23        4.6       3.1       1.5       0.2     setosa        0
24        4.9       3.1       1.5       0.1     setosa        0
25        4.9       3.1       1.5       0.1     setosa        0
26        4.9       3.1       1.5       0.1     setosa        0
27        5.0       3.4       1.5       0.2     setosa        0
28        5.1       3.8       1.5       0.3     setosa        0
29        5.1       3.7       1.5       0.4     setosa        0
..        ...       ...       ...       ...        ...      ...
111       6.4       3.2       5.3       2.3  virginica        2
112       6.2       3.4       5.4       2.3  virginica        2
113       6.9       3.1       5.4       2.1  virginica        2
114       6.4       3.1       5.5       1.8  virginica        2
115       6.5       3.0       5.5       1.8  virginica        2
116       6.8       3.0       5.5       2.1  virginica        2
117       6.1       2.6       5.6       1.4  virginica        2
118       6.3       2.9       5.6       1.8  virginica        2
119       6.3       3.4       5.6       2.4  virginica        2
120       6.4       2.8       5.6       2.1  virginica        2
121       6.4       2.8       5.6       2.2  virginica        2
122       6.7       3.1       5.6       2.4  virginica        2
123       6.7       3.3       5.7       2.1  virginica        2
124       6.7       3.3       5.7       2.5  virginica        2
125       6.9       3.2       5.7       2.3  virginica        2
126       6.5       3.0       5.8       2.2  virginica        2
127       6.7       2.5       5.8       1.8  virginica        2
128       7.2       3.0       5.8       1.6  virginica        2
129       6.8       3.2       5.9       2.3  virginica        2
130       7.1       3.0       5.9       2.1  virginica        2
131       7.2       3.2       6.0       1.8  virginica        2
132       7.2       3.6       6.1       2.5  virginica        2
133       7.4       2.8       6.1       1.9  virginica        2
134       7.7       3.0       6.1       2.3  virginica        2
135       7.3       2.9       6.3       1.8  virginica        2
136       7.9       3.8       6.4       2.0  virginica        2
137       7.6       3.0       6.6       2.1  virginica        2
138       7.7       3.8       6.7       2.2  virginica        2
139       7.7       2.8       6.7       2.0  virginica        2
140       7.7       2.6       6.9       2.3  virginica        2

[141 rows x 6 columns]

In [3]:
#
# different version vary on how to see all rows (adapt to suit your system!)
#
# pd.options.display.max_rows = 150   # None for no limit; default: 10
# pd.options.display.min_rows = 150   # None for no limit; default: 10
# pd.options.display.max_rows = 10   # None for no limit; default: 10
# pd.options.display.min_rows = 10   # None for no limit; default: 10
df_tidy

sepallen  sepalwid  petallen  petalwid   irisname  irisnum
0         4.6       3.6       1.0       0.2     setosa        0
1         4.3       3.0       1.1       0.1     setosa        0
2         5.0       3.2       1.2       0.2     setosa        0
3         5.8       4.0       1.2       0.2     setosa        0
4         4.4       3.0       1.3       0.2     setosa        0
5         4.4       3.2       1.3       0.2     setosa        0
6         4.5       2.3       1.3       0.3     setosa        0
7         4.7       3.2       1.3       0.2     setosa        0
8         5.0       3.5       1.3       0.3     setosa        0
9         5.4       3.9       1.3       0.4     setosa        0
10        5.5       3.5       1.3       0.2     setosa        0
11        4.4       2.9       1.4       0.2     setosa        0
12        4.6       3.4       1.4       0.3     setosa        0
13        4.6       3.2       1.4       0.2     setosa        0
14        4.8       3.0       1.4       0.1     setosa        0
15        4.8       3.0       1.4       0.3     setosa        0
16        4.9       3.0       1.4       0.2     setosa        0
17        5.0       3.6       1.4       0.2     setosa        0
18        5.0       3.3       1.4       0.2     setosa        0
19        5.1       3.5       1.4       0.2     setosa        0
20        5.1       3.5       1.4       0.3     setosa        0
21        5.2       3.4       1.4       0.2     setosa        0
22        5.5       4.2       1.4       0.2     setosa        0
23        4.6       3.1       1.5       0.2     setosa        0
24        4.9       3.1       1.5       0.1     setosa        0
25        4.9       3.1       1.5       0.1     setosa        0
26        4.9       3.1       1.5       0.1     setosa        0
27        5.0       3.4       1.5       0.2     setosa        0
28        5.1       3.8       1.5       0.3     setosa        0
29        5.1       3.7       1.5       0.4     setosa        0
..        ...       ...       ...       ...        ...      ...
111       6.4       3.2       5.3       2.3  virginica        2
112       6.2       3.4       5.4       2.3  virginica        2
113       6.9       3.1       5.4       2.1  virginica        2
114       6.4       3.1       5.5       1.8  virginica        2
115       6.5       3.0       5.5       1.8  virginica        2
116       6.8       3.0       5.5       2.1  virginica        2
117       6.1       2.6       5.6       1.4  virginica        2
118       6.3       2.9       5.6       1.8  virginica        2
119       6.3       3.4       5.6       2.4  virginica        2
120       6.4       2.8       5.6       2.1  virginica        2
121       6.4       2.8       5.6       2.2  virginica        2
122       6.7       3.1       5.6       2.4  virginica        2
123       6.7       3.3       5.7       2.1  virginica        2
124       6.7       3.3       5.7       2.5  virginica        2
125       6.9       3.2       5.7       2.3  virginica        2
126       6.5       3.0       5.8       2.2  virginica        2
127       6.7       2.5       5.8       1.8  virginica        2
128       7.2       3.0       5.8       1.6  virginica        2
129       6.8       3.2       5.9       2.3  virginica        2
130       7.1       3.0       5.9       2.1  virginica        2
131       7.2       3.2       6.0       1.8  virginica        2
132       7.2       3.6       6.1       2.5  virginica        2
133       7.4       2.8       6.1       1.9  virginica        2
134       7.7       3.0       6.1       2.3  virginica        2
135       7.3       2.9       6.3       1.8  virginica        2
136       7.9       3.8       6.4       2.0  virginica        2
137       7.6       3.0       6.6       2.1  virginica        2
138       7.7       3.8       6.7       2.2  virginica        2
139       7.7       2.8       6.7       2.0  virginica        2
140       7.7       2.6       6.9       2.3  virginica        2

[141 rows x 6 columns]

In [4]:
#
# Let's drop the columns we don't want/need -- or that we shouldn't have...!
#

# First, look at the info:
df_tidy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 141 entries, 0 to 140
Data columns (total 6 columns):
sepallen    141 non-null float64
sepalwid    141 non-null float64
petallen    141 non-null float64
petalwid    141 non-null float64
irisname    141 non-null object
irisnum     141 non-null int64
dtypes: float64(4), int64(1), object(1)
memory usage: 7.7+ KB


In [5]:
#
# All of the columns need to be numeric, we'll drop irisname
ROW = 0
COLUMN = 1
df_model1 = df_tidy.drop( 'irisname', axis=COLUMN )
df_model1

sepallen  sepalwid  petallen  petalwid  irisnum
0         4.6       3.6       1.0       0.2        0
1         4.3       3.0       1.1       0.1        0
2         5.0       3.2       1.2       0.2        0
3         5.8       4.0       1.2       0.2        0
4         4.4       3.0       1.3       0.2        0
5         4.4       3.2       1.3       0.2        0
6         4.5       2.3       1.3       0.3        0
7         4.7       3.2       1.3       0.2        0
8         5.0       3.5       1.3       0.3        0
9         5.4       3.9       1.3       0.4        0
10        5.5       3.5       1.3       0.2        0
11        4.4       2.9       1.4       0.2        0
12        4.6       3.4       1.4       0.3        0
13        4.6       3.2       1.4       0.2        0
14        4.8       3.0       1.4       0.1        0
15        4.8       3.0       1.4       0.3        0
16        4.9       3.0       1.4       0.2        0
17        5.0       3.6       1.4       0.2        0
18        5.0       3.3       1.4       0.2        0
19        5.1       3.5       1.4       0.2        0
20        5.1       3.5       1.4       0.3        0
21        5.2       3.4       1.4       0.2        0
22        5.5       4.2       1.4       0.2        0
23        4.6       3.1       1.5       0.2        0
24        4.9       3.1       1.5       0.1        0
25        4.9       3.1       1.5       0.1        0
26        4.9       3.1       1.5       0.1        0
27        5.0       3.4       1.5       0.2        0
28        5.1       3.8       1.5       0.3        0
29        5.1       3.7       1.5       0.4        0
..        ...       ...       ...       ...      ...
111       6.4       3.2       5.3       2.3        2
112       6.2       3.4       5.4       2.3        2
113       6.9       3.1       5.4       2.1        2
114       6.4       3.1       5.5       1.8        2
115       6.5       3.0       5.5       1.8        2
116       6.8       3.0       5.5       2.1        2
117       6.1       2.6       5.6       1.4        2
118       6.3       2.9       5.6       1.8        2
119       6.3       3.4       5.6       2.4        2
120       6.4       2.8       5.6       2.1        2
121       6.4       2.8       5.6       2.2        2
122       6.7       3.1       5.6       2.4        2
123       6.7       3.3       5.7       2.1        2
124       6.7       3.3       5.7       2.5        2
125       6.9       3.2       5.7       2.3        2
126       6.5       3.0       5.8       2.2        2
127       6.7       2.5       5.8       1.8        2
128       7.2       3.0       5.8       1.6        2
129       6.8       3.2       5.9       2.3        2
130       7.1       3.0       5.9       2.1        2
131       7.2       3.2       6.0       1.8        2
132       7.2       3.6       6.1       2.5        2
133       7.4       2.8       6.1       1.9        2
134       7.7       3.0       6.1       2.3        2
135       7.3       2.9       6.3       1.8        2
136       7.9       3.8       6.4       2.0        2
137       7.6       3.0       6.6       2.1        2
138       7.7       3.8       6.7       2.2        2
139       7.7       2.8       6.7       2.0        2
140       7.7       2.6       6.9       2.3        2

[141 rows x 5 columns]

In [6]:
#
# once we have all the columns we want, let's create an index of their names...

#
# Let's make sure we have all of our helpful variables in one place 
#       To be adapted if we drop/add more columns...
#

#
# let's keep our column names in variables, for reference
#
COLUMNS = df_model1.columns            # "list" of columns
print(f"COLUMNS is {COLUMNS}\n")  
  # It's a "pandas" list, called an Index
  # use it just as a Python list of strings:
print(f"COLUMNS[0] is {COLUMNS[0]}\n")

# let's create a dictionary to look up any column index by name
COL_INDEX = {}
for i, name in enumerate(COLUMNS):
    COL_INDEX[name] = i  # using the name (as key), look up the value (i)
print(f"COL_INDEX is {COL_INDEX}\n\n")


#
# and our "species" names
#

# all of scikit-learn's ML routines need numbers, not strings
#   ... even for categories/classifications (like species!)
#   so, we will convert the flower-species to numbers:

SPECIES = ['setosa','versicolor','virginica']   # int to str
SPECIES_INDEX = {'setosa':0,'versicolor':1,'virginica':2}  # str to int

# Let's try it out...
for name in SPECIES:
    print(f"{name} maps to {SPECIES_INDEX[name]}")

COLUMNS is Index(['sepallen', 'sepalwid', 'petallen', 'petalwid', 'irisnum'], dtype='object')

COLUMNS[0] is sepallen

COL_INDEX is {'sepallen': 0, 'sepalwid': 1, 'petallen': 2, 'petalwid': 3, 'irisnum': 4}


setosa maps to 0
versicolor maps to 1
virginica maps to 2


In [7]:
#
# We _could_ reweight our columns...
# What if petalwid is "worth" 20x more than the others?
# 
df_model1['petalwid'] *= 20
df_model1


sepallen  sepalwid  petallen  petalwid  irisnum
0         4.6       3.6       1.0       4.0        0
1         4.3       3.0       1.1       2.0        0
2         5.0       3.2       1.2       4.0        0
3         5.8       4.0       1.2       4.0        0
4         4.4       3.0       1.3       4.0        0
5         4.4       3.2       1.3       4.0        0
6         4.5       2.3       1.3       6.0        0
7         4.7       3.2       1.3       4.0        0
8         5.0       3.5       1.3       6.0        0
9         5.4       3.9       1.3       8.0        0
10        5.5       3.5       1.3       4.0        0
11        4.4       2.9       1.4       4.0        0
12        4.6       3.4       1.4       6.0        0
13        4.6       3.2       1.4       4.0        0
14        4.8       3.0       1.4       2.0        0
15        4.8       3.0       1.4       6.0        0
16        4.9       3.0       1.4       4.0        0
17        5.0       3.6       1.4       4.0        0
18        5.0       3.3       1.4       4.0        0
19        5.1       3.5       1.4       4.0        0
20        5.1       3.5       1.4       6.0        0
21        5.2       3.4       1.4       4.0        0
22        5.5       4.2       1.4       4.0        0
23        4.6       3.1       1.5       4.0        0
24        4.9       3.1       1.5       2.0        0
25        4.9       3.1       1.5       2.0        0
26        4.9       3.1       1.5       2.0        0
27        5.0       3.4       1.5       4.0        0
28        5.1       3.8       1.5       6.0        0
29        5.1       3.7       1.5       8.0        0
..        ...       ...       ...       ...      ...
111       6.4       3.2       5.3      46.0        2
112       6.2       3.4       5.4      46.0        2
113       6.9       3.1       5.4      42.0        2
114       6.4       3.1       5.5      36.0        2
115       6.5       3.0       5.5      36.0        2
116       6.8       3.0       5.5      42.0        2
117       6.1       2.6       5.6      28.0        2
118       6.3       2.9       5.6      36.0        2
119       6.3       3.4       5.6      48.0        2
120       6.4       2.8       5.6      42.0        2
121       6.4       2.8       5.6      44.0        2
122       6.7       3.1       5.6      48.0        2
123       6.7       3.3       5.7      42.0        2
124       6.7       3.3       5.7      50.0        2
125       6.9       3.2       5.7      46.0        2
126       6.5       3.0       5.8      44.0        2
127       6.7       2.5       5.8      36.0        2
128       7.2       3.0       5.8      32.0        2
129       6.8       3.2       5.9      46.0        2
130       7.1       3.0       5.9      42.0        2
131       7.2       3.2       6.0      36.0        2
132       7.2       3.6       6.1      50.0        2
133       7.4       2.8       6.1      38.0        2
134       7.7       3.0       6.1      46.0        2
135       7.3       2.9       6.3      36.0        2
136       7.9       3.8       6.4      40.0        2
137       7.6       3.0       6.6      42.0        2
138       7.7       3.8       6.7      44.0        2
139       7.7       2.8       6.7      40.0        2
140       7.7       2.6       6.9      46.0        2

[141 rows x 5 columns]

In [8]:
# Until we have more insight, this seems arbitrary at best (or data-rigging, worse...)
# Let's set it back...
df_model1['petalwid'] /= 20
df_model1


sepallen  sepalwid  petallen  petalwid  irisnum
0         4.6       3.6       1.0       0.2        0
1         4.3       3.0       1.1       0.1        0
2         5.0       3.2       1.2       0.2        0
3         5.8       4.0       1.2       0.2        0
4         4.4       3.0       1.3       0.2        0
5         4.4       3.2       1.3       0.2        0
6         4.5       2.3       1.3       0.3        0
7         4.7       3.2       1.3       0.2        0
8         5.0       3.5       1.3       0.3        0
9         5.4       3.9       1.3       0.4        0
10        5.5       3.5       1.3       0.2        0
11        4.4       2.9       1.4       0.2        0
12        4.6       3.4       1.4       0.3        0
13        4.6       3.2       1.4       0.2        0
14        4.8       3.0       1.4       0.1        0
15        4.8       3.0       1.4       0.3        0
16        4.9       3.0       1.4       0.2        0
17        5.0       3.6       1.4       0.2        0
18        5.0       3.3       1.4       0.2        0
19        5.1       3.5       1.4       0.2        0
20        5.1       3.5       1.4       0.3        0
21        5.2       3.4       1.4       0.2        0
22        5.5       4.2       1.4       0.2        0
23        4.6       3.1       1.5       0.2        0
24        4.9       3.1       1.5       0.1        0
25        4.9       3.1       1.5       0.1        0
26        4.9       3.1       1.5       0.1        0
27        5.0       3.4       1.5       0.2        0
28        5.1       3.8       1.5       0.3        0
29        5.1       3.7       1.5       0.4        0
..        ...       ...       ...       ...      ...
111       6.4       3.2       5.3       2.3        2
112       6.2       3.4       5.4       2.3        2
113       6.9       3.1       5.4       2.1        2
114       6.4       3.1       5.5       1.8        2
115       6.5       3.0       5.5       1.8        2
116       6.8       3.0       5.5       2.1        2
117       6.1       2.6       5.6       1.4        2
118       6.3       2.9       5.6       1.8        2
119       6.3       3.4       5.6       2.4        2
120       6.4       2.8       5.6       2.1        2
121       6.4       2.8       5.6       2.2        2
122       6.7       3.1       5.6       2.4        2
123       6.7       3.3       5.7       2.1        2
124       6.7       3.3       5.7       2.5        2
125       6.9       3.2       5.7       2.3        2
126       6.5       3.0       5.8       2.2        2
127       6.7       2.5       5.8       1.8        2
128       7.2       3.0       5.8       1.6        2
129       6.8       3.2       5.9       2.3        2
130       7.1       3.0       5.9       2.1        2
131       7.2       3.2       6.0       1.8        2
132       7.2       3.6       6.1       2.5        2
133       7.4       2.8       6.1       1.9        2
134       7.7       3.0       6.1       2.3        2
135       7.3       2.9       6.3       1.8        2
136       7.9       3.8       6.4       2.0        2
137       7.6       3.0       6.6       2.1        2
138       7.7       3.8       6.7       2.2        2
139       7.7       2.8       6.7       2.0        2
140       7.7       2.6       6.9       2.3        2

[141 rows x 5 columns]

In [9]:
#
A = df_model1.to_numpy()    # .values gets the numpy array
print(A)


[[4.6 3.6 1.  0.2 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [4.6 3.2 1.4 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.8 3.  1.4 0.3 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.  3.3 1.4 0.2 0. ]
 [5.1 3.5 1.4 0.2 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.3 3.7 1.5 0.2 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.  3.5 1.6 0.6 0. ]
 [5.1 3.8 1.6 0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [5.4 3.4 1

In [10]:

#
# let's make sure it's all floating-point, so we can multiply and divide
#
A = A.astype('float64')  # so many types:  www.tutorialspoint.com/numpy/numpy_data_types.htm
print(A)


[[4.6 3.6 1.  0.2 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [4.6 3.2 1.4 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.8 3.  1.4 0.3 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.  3.3 1.4 0.2 0. ]
 [5.1 3.5 1.4 0.2 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.3 3.7 1.5 0.2 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.  3.5 1.6 0.6 0. ]
 [5.1 3.8 1.6 0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [5.4 3.4 1

In [11]:
#
# Also, nice to have NUM_ROWS and NUM_COLS around
#
NUM_ROWS, NUM_COLS = A.shape
print(f"\nThe dataset has {NUM_ROWS} rows and {NUM_COLS} cols")


The dataset has 141 rows and 5 cols


In [12]:
# let's use all of our variables, to reinforce that we have
# (1) names...
# (2) access and control...

# choose a row index, n:
n = 42
print(f"flower #{n} is {A[n]}")

for i in range(len(COLUMNS)):
    colname = COLUMNS[i]
    value = A[n][i]
    print(f"  Its {colname} is {value}")

species_index = COL_INDEX['irisnum']
species_num = int(round(A[n][species_index]))
species = SPECIES[species_num]
print(f"  Its species is {species} (i.e., {species_num})")


flower #42 is [5.4 3.9 1.7 0.4 0. ]
  Its sepallen is 5.4
  Its sepalwid is 3.9
  Its petallen is 1.7
  Its petalwid is 0.4
  Its irisnum is 0.0
  Its species is setosa (i.e., 0)


In [13]:
print("+++ Start of data definitions +++\n")

#
# we could do this at the data-frame level, too!
#

X_all = A[:,0:4]  # X (features) ... is all rows, columns 0, 1, 2, 3
y_all = A[:,4]    # y (labels) ... is all rows, column 4 only

print(f"y_all (just the labels/species)   are \n {y_all}")
print(f"X_all (just the features) are \n {X_all}")


+++ Start of data definitions +++

y_all (just the labels/species)   are 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
X_all (just the features) are 
 [[4.6 3.6 1.  0.2]
 [4.3 3.  1.1 0.1]
 [5.  3.2 1.2 0.2]
 [5.8 4.  1.2 0.2]
 [4.4 3.  1.3 0.2]
 [4.4 3.2 1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.7 3.2 1.3 0.2]
 [5.  3.5 1.3 0.3]
 [5.4 3.9 1.3 0.4]
 [5.5 3.5 1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 3.2 1.4 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.  1.4 0.3]
 [4.9 3.  1.4 0.2]
 [5.  3.6 1.4 0.2]
 [5.  3.3 1.4 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.5 1.4 0.3]
 [5.2 3.4 1.4 0.2]
 [5.5 4.2 1.4 0.2]
 [4.6 3.1 1.5 0.2]
 [4.9 3

In [14]:
#
# we scramble the data, to remove (potential) dependence on its ordering: 
# 
indices = np.random.permutation(len(y_all))  # indices is a permutation-list

# we scramble both X and y, necessarily with the same permutation
X_labeled = X_all[indices]              # we apply the _same_ permutation to each!
y_labeled = y_all[indices]              # again...
print(f"The scrambled labels/species are \n {y_labeled}")
print(f"The corresponding data rows are \n {X_labeled}")


The scrambled labels/species are 
 [1. 0. 1. 1. 2. 0. 1. 1. 0. 2. 2. 0. 1. 2. 0. 1. 1. 1. 1. 0. 0. 1. 0. 2.
 1. 0. 0. 2. 0. 1. 2. 2. 1. 0. 1. 2. 1. 1. 2. 1. 1. 2. 2. 2. 0. 0. 0. 0.
 1. 2. 2. 0. 2. 0. 2. 1. 1. 1. 0. 1. 1. 0. 0. 2. 2. 1. 0. 0. 0. 0. 1. 2.
 0. 0. 2. 2. 0. 2. 1. 2. 0. 2. 1. 1. 0. 2. 2. 1. 1. 0. 1. 0. 2. 2. 2. 1.
 2. 0. 2. 0. 0. 1. 0. 2. 1. 0. 1. 0. 0. 1. 2. 2. 0. 2. 2. 2. 0. 2. 1. 1.
 0. 0. 1. 0. 1. 1. 2. 0. 1. 2. 2. 2. 0. 2. 1. 1. 0. 2. 2. 2. 2.]
The corresponding data rows are 
 [[5.6 3.  4.5 1.5]
 [5.  3.6 1.4 0.2]
 [6.3 3.3 4.7 1.6]
 [6.3 2.3 4.4 1.3]
 [6.7 3.  5.2 2.3]
 [5.5 3.5 1.3 0.2]
 [5.  2.  3.5 1. ]
 [5.5 2.6 4.4 1.2]
 [4.9 3.1 1.5 0.1]
 [6.7 3.3 5.7 2.1]
 [6.7 2.5 5.8 1.8]
 [5.  3.4 1.5 0.2]
 [6.4 2.9 4.3 1.3]
 [6.7 3.3 5.7 2.5]
 [5.1 3.8 1.5 0.3]
 [5.6 2.7 4.2 1.3]
 [5.5 2.5 4.  1.3]
 [6.4 3.2 4.5 1.5]
 [6.2 2.2 4.5 1.5]
 [4.9 3.1 1.5 0.1]
 [5.1 3.5 1.4 0.2]
 [4.9 2.4 3.3 1. ]
 [5.8 4.  1.2 0.2]
 [6.2 3.4 5.4 2.3]
 [6.5 2.8 4.6 1.5]
 [4.9 3.1 1.5 0.1]
 [4.6 3

In [15]:
#
# We next separate into test data and training data ... 
#    + We will train on the training data...
#    + We will _not_ look at the testing data to build the model
#
# Then, afterward, we will test on the testing data -- and see how well we do!
#

#
# a common convention:  train on 80%, test on 20%    Let's define the TEST_PERCENT
#

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2, random_state=42)

print(f"training with {len(y_train)} rows;  testing with {len(y_test)} rows\n" )

print(f"Held-out data... (testing data: {len(y_test)})")
print(f"y_test: {y_test}")
print(f"X_test (a few rows): {X_test[0:5,:]}")  # 5 rows
print()
print(f"Data used for modeling... (training data: {len(y_train)})")
print(f"y_train: {y_train}")
print(f"X_train (a few rows): {X_train[0:5,:]}")  # 5 rows

training with 112 rows;  testing with 29 rows

Held-out data... (testing data: 29)
y_test: [1. 2. 0. 1. 2. 2. 1. 2. 2. 0. 0. 0. 0. 2. 2. 2. 0. 2. 0. 2. 1. 2. 2. 2.
 1. 0. 1. 0. 2.]
X_test (a few rows): [[6.4 2.9 4.3 1.3]
 [6.5 3.  5.2 2. ]
 [5.2 3.5 1.5 0.2]
 [5.7 2.6 3.5 1. ]
 [6.2 2.8 4.8 1.8]]

Data used for modeling... (training data: 112)
y_train: [2. 0. 0. 0. 0. 1. 1. 2. 1. 2. 1. 0. 1. 0. 0. 0. 0. 2. 1. 1. 0. 0. 2. 0.
 0. 1. 1. 2. 1. 0. 1. 2. 2. 0. 0. 1. 2. 1. 1. 1. 1. 0. 1. 1. 1. 0. 0. 2.
 0. 0. 1. 1. 2. 2. 0. 0. 2. 0. 0. 0. 1. 2. 0. 2. 2. 2. 1. 1. 2. 0. 2. 1.
 2. 1. 2. 1. 0. 1. 1. 1. 1. 2. 2. 1. 1. 0. 2. 1. 1. 2. 0. 0. 2. 2. 0. 1.
 0. 0. 0. 2. 2. 2. 1. 1. 2. 2. 0. 1. 2. 0. 1. 2.]
X_train (a few rows): [[6.9 3.1 5.4 2.1]
 [4.9 3.  1.4 0.2]
 [5.  3.3 1.4 0.2]
 [5.5 3.5 1.3 0.2]
 [4.8 3.4 1.6 0.2]]


<br>

#### Here is where the model-buidling begins in earnest...

In [16]:
#
# +++ This is the "Model-building and Model-training Cell"
#       
# Create a kNN model and train it! 
#
from sklearn.neighbors import KNeighborsClassifier

k = 84   # we don't know what k to use, so we guess!  (this will _not_ be a good value)
knn_model = KNeighborsClassifier(n_neighbors=k)       # here, k is the "k" in kNN

# we train the model (it's one line!)
knn_model.fit(X_train, y_train)                              # yay!  trained!
print("Created and trained a knn classifier with k =", k)  

Created and trained a knn classifier with k = 84


<br>

#### That's it! :-)

In [17]:
#
# +++ This cell will "Model-testing Cell"
#
# Now, let's see how well our model does on our "held-out data" (the testing data)
#

# We run our test set:

# the function knn_model.predict is the instantiation of our model
# it's what runs the k-nearest-neighbors algorithm:
predicted_labels = knn_model.predict(X_test)   
actual_labels = y_test

# Let's print them so we can compare...
print("Predicted labels:", predicted_labels)
print("Actual  labels  :", actual_labels)

# And, some overall results
num_correct = sum(predicted_labels == actual_labels)
total = len(actual_labels)
print(f"\nResults on test set:  {num_correct} correct out of {total} total.")

Predicted labels: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1.
 1. 0. 1. 1. 1.]
Actual  labels  : [1. 2. 0. 1. 2. 2. 1. 2. 2. 0. 0. 0. 0. 2. 2. 2. 0. 2. 0. 2. 1. 2. 2. 2.
 1. 0. 1. 0. 2.]

Results on test set:  8 correct out of 29 total.


In [18]:
#
# Let's print these more helpfully, in a vertical table
#

def compare_labels(predicted_labels, actual_labels):
    """ a more neatly formatted comparison """
    NUM_LABELS = len(predicted_labels)
    num_correct = 0
    
    for i in range(NUM_LABELS):
        p = int(round(predicted_labels[i]))         # round protects from fp error 
        a = int(round(actual_labels[i]))
        result = "incorrect"
        if p == a:  # if they match,
            result = ""       # no longer incorrect
            num_correct += 1  # and we count a match!

        print(f"row {i:>3d} : {SPECIES[p]:>12s} {SPECIES[a]:<12s}   {result}")   

    print()
    print("Correct:", num_correct, "out of", NUM_LABELS)
    return num_correct

# let's try it out!
compare_labels(predicted_labels,actual_labels)

row   0 :   versicolor versicolor     
row   1 :   versicolor virginica      incorrect
row   2 :   versicolor setosa         incorrect
row   3 :   versicolor versicolor     
row   4 :   versicolor virginica      incorrect
row   5 :   versicolor virginica      incorrect
row   6 :   versicolor versicolor     
row   7 :   versicolor virginica      incorrect
row   8 :   versicolor virginica      incorrect
row   9 :   versicolor setosa         incorrect
row  10 :   versicolor setosa         incorrect
row  11 :   versicolor setosa         incorrect
row  12 :   versicolor setosa         incorrect
row  13 :   versicolor virginica      incorrect
row  14 :   versicolor virginica      incorrect
row  15 :   versicolor virginica      incorrect
row  16 :   versicolor setosa         incorrect
row  17 :   versicolor virginica      incorrect
row  18 :       setosa setosa         
row  19 :   versicolor virginica      incorrect
row  20 :   versicolor versicolor     
row  21 :   versicolor virginica     

8

In [19]:
#
# Ok!  We have our knn model, we could just use it...
#

#
# data-driven predictive model (k-nearest-neighbor), using scikit-learn
#

# warning: this model has not yet been tuned to its "best k"
def predictive_model( Features ):
    """ input: a list of four features 
                [ sepallen, sepalwid, petallen, petalwid ]
        output: the predicted species of iris, from
                  setosa (0), versicolor (1), virginica (2)
    """
    our_features = np.asarray([Features])                 # extra brackets needed
    predicted_species = knn_model.predict(our_features)
    
    predicted_species = int(round(predicted_species[0]))  # unpack one element
    name = SPECIES[predicted_species]
    return f"{name} ({predicted_species})"
    
#
# Try it!
# 
# Features = eval(input("Enter new Features: "))
#
Features = [6.7,3.3,5.7,2.1]  # [5.8,2.7,4.1,1.0] [4.6,3.6,3.0,2.2] [6.7,3.3,5.7,2.1]
result = predictive_model( Features )
print(f"I predict {result} from Features {Features}")

I predict versicolor (1) from Features [6.7, 3.3, 5.7, 2.1]


In [ ]:
#
# Except, we didn't really explore whether this was the BEST model we could build!
#
#
# We used k = 84  (a neighborhood size of 84 flowers)
# In a dataset of only 140ish flowers, with three species, this seems like a _bad_ idea!
#
# Perhaps we should try ALL the neighborhood sizes in their own TRAIN/TEST split
# and see which neighborhood size works the best, for irises, at least...
#

In [20]:
#
# to do this, we use "cross validation"
#

from sklearn.model_selection import cross_val_score

#
# cross-validation splits the training set into two pieces:
#   + model-building and model-validation. We'll use "build" and "validate"
#
best_k = 84  # Not correct!
best_accuracy = 0.0  # also not correct...

# Note that we are cross-validating using only our TEST data!
for k in range(1,85):
    knn_cv_model = KNeighborsClassifier(n_neighbors=k)   # build knn_model for every k!
    cv_scores = cross_val_score( knn_cv_model, X_train, y_train, cv=5 )  # cv=5 means 80/20
    print(cv_scores)  # just to see the five scores... 
    average_cv_accuracy = cv_scores.mean()  # mean() is numpy's built-in average function 
    print(f"k: {k:2d}  cv accuracy: {average_cv_accuracy:7.4f}")

    
# assign best value of k to best_k
    if average_cv_accuracy > best_accuracy:
        best_accuracy = average_cv_accuracy
        best_k = k      # at the moment this is incorrect   TO DO for hw4pr1: fix this...
# you'll need to use the loop above to find and remember the real best_k

print(f"best_k = {best_k}   yields the highest average cv accuracy.")  # print the best one

#
# Your task:  
#    is to use this loop to remember the best value of k in the variable best_k
#    (feel free to use best_k and best_accuracy, above)     
#     

[1.         0.95652174 0.95652174 1.         0.85714286]
k:  1  cv accuracy:  0.9540
[0.95652174 0.91304348 0.91304348 1.         0.85714286]
k:  2  cv accuracy:  0.9280
[0.95652174 0.91304348 0.95652174 0.95454545 0.9047619 ]
k:  3  cv accuracy:  0.9371
[0.91304348 0.91304348 0.95652174 1.         0.95238095]
k:  4  cv accuracy:  0.9470
[1.         0.91304348 0.95652174 0.95454545 0.95238095]
k:  5  cv accuracy:  0.9553
[1.         0.91304348 0.95652174 0.95454545 0.95238095]
k:  6  cv accuracy:  0.9553
[1.         0.91304348 1.         0.95454545 0.95238095]
k:  7  cv accuracy:  0.9640
[1.         0.91304348 0.95652174 1.         0.95238095]
k:  8  cv accuracy:  0.9644
[1.         0.95652174 0.95652174 0.95454545 0.95238095]
k:  9  cv accuracy:  0.9640
[0.95652174 0.91304348 0.95652174 0.95454545 0.95238095]
k: 10  cv accuracy:  0.9466
[1.         0.91304348 0.95652174 0.95454545 0.95238095]
k: 11  cv accuracy:  0.9553
[1.         0.91304348 0.95652174 0.95454545 0.95238095]
k: 12  c

In [21]:
#
# With the best k, we build and train a new model:
#
# Now, we use best_k instead of the original, randomly-guessed value    
#
best_k = 7
from sklearn.neighbors import KNeighborsClassifier
knn_model_tuned = KNeighborsClassifier(n_neighbors=best_k)   # here, we use the best_k!

# we train the model (one line!)
knn_model_tuned.fit(X_train, y_train)                              # yay!  trained!
print(f"Created + trained a knn classifier, now tuned with a (best) k of {best_k}")  

# How does it do?!  The next cell will show...

Created + trained a knn classifier, now tuned with a (best) k of 7


In [22]:
#
# Re-create and re-run the  "Model-testing Cell"     How does it do with best_k?!
#
predicted_labels = knn_model_tuned.predict(X_test)
actual_labels = y_test

# Let's print them so we can compare...
print("Predicted labels:", predicted_labels)
print("Actual labels:", actual_labels)

# And, the overall results
num_correct = sum(predicted_labels == actual_labels)
total = len(actual_labels)
print(f"\nResults on test set:  {num_correct} correct out of {total} total.\n\n")

# Plus, we'll print our nicer table...
compare_labels(predicted_labels,actual_labels)

Predicted labels: [1. 2. 0. 1. 2. 2. 1. 2. 2. 0. 0. 0. 0. 1. 2. 2. 0. 2. 0. 2. 1. 1. 2. 2.
 1. 0. 1. 0. 1.]
Actual labels: [1. 2. 0. 1. 2. 2. 1. 2. 2. 0. 0. 0. 0. 2. 2. 2. 0. 2. 0. 2. 1. 2. 2. 2.
 1. 0. 1. 0. 2.]

Results on test set:  26 correct out of 29 total.


row   0 :   versicolor versicolor     
row   1 :    virginica virginica      
row   2 :       setosa setosa         
row   3 :   versicolor versicolor     
row   4 :    virginica virginica      
row   5 :    virginica virginica      
row   6 :   versicolor versicolor     
row   7 :    virginica virginica      
row   8 :    virginica virginica      
row   9 :       setosa setosa         
row  10 :       setosa setosa         
row  11 :       setosa setosa         
row  12 :       setosa setosa         
row  13 :   versicolor virginica      incorrect
row  14 :    virginica virginica      
row  15 :    virginica virginica      
row  16 :       setosa setosa         
row  17 :    virginica virginica      
row  18 :       setosa 

26

In [23]:
#
# Ok!  We have tuned knn to use the "best" value of k...
#
# And, we should now use ALL available data to train our final predictive model:
#

knn_model_final = KNeighborsClassifier(n_neighbors=best_k)   # here, we use the best_k
knn_model_final.fit(X_all, y_all)                              # here we use ALL the data!
print(f"Created + trained a 'final' knn classifier, with a (best) k of {best_k}") 

Created + trained a 'final' knn classifier, with a (best) k of 7


In [24]:
#
# final predictive model (k-nearest-neighbor), with tuned k + ALL data incorporated
#

def predictive_model( Features, Model ):
    """ input: a list of four features 
                [ sepallen, sepalwid, petallen, petalwid ]
        output: the predicted species of iris, from
                  setosa (0), versicolor (1), virginica (2)
    """
    our_features = np.asarray([Features])                 # extra brackets needed

    # The model's prediction!
    predicted_species = Model.predict(our_features)
    
    # a bit awkward
    predicted_species = int(round(predicted_species[0]))  # unpack one element
    return predicted_species

    
#
# Try it!
# 
# Features = eval(input("Enter new Features: "))
#
Features = [6.7,3.3,5.7,0.1]  # [5.8,2.7,4.1,1.0] [4.6,3.6,3.0,2.2] [6.7,3.3,5.7,2.1]

LoF = [
[4.8, 3.1, 1.6, 0.2 ],
[5.7, 2.9, 4.2, 1.3 ],
[5.8, 2.7, 5.1, 1.9 ],
[5.2, 4.1, 1.5, 0.1 ],
[5.4, 3.4, 1.5, 0.4 ],
[5.1, 2.5, 3.0, 1.1 ],
[6.2, 2.9, 4.3, 1.3 ],
[6.3, 3.3, 6.0, 2.5 ],
[5.7, 2.8, 4.1, 1.3 ],
  ]

# run on each one:
for Features in LoF:
    predicted_species = predictive_model( Features, knn_model_final )  # pass in the model, too!
    name = SPECIES[predicted_species]
    print(f"I predict {name} from the features {Features}")

I predict setosa from the features [4.8, 3.1, 1.6, 0.2]
I predict versicolor from the features [5.7, 2.9, 4.2, 1.3]
I predict virginica from the features [5.8, 2.7, 5.1, 1.9]
I predict setosa from the features [5.2, 4.1, 1.5, 0.1]
I predict setosa from the features [5.4, 3.4, 1.5, 0.4]
I predict versicolor from the features [5.1, 2.5, 3.0, 1.1]
I predict versicolor from the features [6.2, 2.9, 4.3, 1.3]
I predict virginica from the features [6.3, 3.3, 6.0, 2.5]
I predict versicolor from the features [5.7, 2.8, 4.1, 1.3]


In [ ]:
#
# That's it!  Welcome to the world of model-building workflows!!    
#
#             Our prediction?  We'll be back for more ML! 
#

#
# In fact, the rest of the hw is to run more ML workflows:   Births, Digits, Titanic, (ec) Housing, ...
#