In [ ]:
#
# hw4pr3titanic:  titanic-passenger clasification via nearest neighbors
#

In [ ]:
#
# SUGGESTION:  
# 
# +++ copy-paste-and-alter from the iris- + births + digits-cleaning notebooks into here +++
#
# Here, there can be value in weighting columns with different coefficients... explore!
#

In [1]:
# libraries!
import numpy as np      # numpy is Python's "array" library
import pandas as pd     # Pandas is Python's "data" library ("dataframe" == spreadsheet)

In [2]:
df_tidy = pd.read_csv('titanic_cleaned.csv')
df_tidy

pclass  survived     sex      age  sibsp  parch  sexnum
0          1         1  female  29.0000      0      0       0
1          1         1    male   0.9167      1      2       1
2          1         0  female   2.0000      1      2       0
3          1         0    male  30.0000      1      2       1
4          1         0  female  25.0000      1      2       0
...      ...       ...     ...      ...    ...    ...     ...
1259       3         0    male  45.5000      0      0       1
1262       3         0  female  14.5000      1      0       0
1264       3         0    male  26.5000      0      0       1
1265       3         0    male  27.0000      0      0       1
1266       3         0    male  29.0000      0      0       1

[1004 rows x 7 columns]

In [3]:
ROW = 0
COLUMN = 1
df_model1 = df_tidy.drop('sex', axis=COLUMN )
df_model1

pclass  survived      age  sibsp  parch  sexnum
0          1         1  29.0000      0      0       0
1          1         1   0.9167      1      2       1
2          1         0   2.0000      1      2       0
3          1         0  30.0000      1      2       1
4          1         0  25.0000      1      2       0
...      ...       ...      ...    ...    ...     ...
1259       3         0  45.5000      0      0       1
1262       3         0  14.5000      1      0       0
1264       3         0  26.5000      0      0       1
1265       3         0  27.0000      0      0       1
1266       3         0  29.0000      0      0       1

[1004 rows x 6 columns]

In [4]:
#
A = df_model1.to_numpy().astype('float64')
print(A)

[[ 1.      1.     29.      0.      0.      0.    ]
 [ 1.      1.      0.9167  1.      2.      1.    ]
 [ 1.      0.      2.      1.      2.      0.    ]
 ...
 [ 3.      0.     26.5     0.      0.      1.    ]
 [ 3.      0.     27.      0.      0.      1.    ]
 [ 3.      0.     29.      0.      0.      1.    ]]


In [16]:
X_all = np.concatenate((A[:, 0].reshape(len(A), 1), A[:, 2:]), axis = 1)
y_all = A[:,1]    

In [17]:
print(f"y_all (just the labels/species)   are \n {y_all}")
print(f"X_all (just the features) are \n {X_all}")

y_all (just the labels/species)   are 
 [1. 1. 0. ... 0. 0. 0.]
X_all (just the features) are 
 [[ 1.     29.      0.      0.      0.    ]
 [ 1.      0.9167  1.      2.      1.    ]
 [ 1.      2.      1.      2.      0.    ]
 ...
 [ 3.     26.5     0.      0.      1.    ]
 [ 3.     27.      0.      0.      1.    ]
 [ 3.     29.      0.      0.      1.    ]]


In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2, random_state=42)

print(f"training with {len(y_train)} rows;  testing with {len(y_test)} rows\n" )

print(f"Held-out data... (testing data: {len(y_test)})")
print(f"y_test: {y_test}")
print(f"X_test (a few rows): {X_test[0:5,:]}")  # 5 rows
print()
print(f"Data used for modeling... (training data: {len(y_train)})")
print(f"y_train: {y_train}")
print(f"X_train (a few rows): {X_train[0:5,:]}")  # 5 rows

training with 803 rows;  testing with 201 rows

Held-out data... (testing data: 201)
y_test: [0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1.
 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 0. 1.
 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1.
 1. 0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0.
 0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0.
 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0.
 0. 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0.
 1. 0. 0. 1. 1. 0. 0. 1. 0.]
X_test (a few rows): [[ 3. 22.  0.  0.  1.]
 [ 3. 19.  0.  0.  1.]
 [ 3. 39.  0.  2.  1.]
 [ 3. 35.  1.  1.  0.]
 [ 2. 28.  0.  1.  1.]]

Data used for modeling... (training data: 803)
y_train: [0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 1.
 1. 0. 0. 0. 0. 0. 0. 0. 1.

In [19]:
from sklearn.neighbors import KNeighborsClassifier

k = 84   # we don't know what k to use, so we guess!  (this will _not_ be a good value)
knn_model = KNeighborsClassifier(n_neighbors=k)       # here, k is the "k" in kNN

# we train the model (it's one line!)
knn_model.fit(X_train, y_train)                              # yay!  trained!
print("Created and trained a knn classifier with k =", k)  

Created and trained a knn classifier with k = 84


In [20]:
predicted_labels = knn_model.predict(X_test)   
actual_labels = y_test

# Let's print them so we can compare...
print("Predicted labels:", predicted_labels)
print("Actual  labels  :", actual_labels)

# And, some overall results
num_correct = sum(predicted_labels == actual_labels)
total = len(actual_labels)
print(f"\nResults on test set:  {num_correct} correct out of {total} total.")

Predicted labels: [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 1. 0.]
Actual  labels  : [0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1.
 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 0. 1.
 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1.
 1. 0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0.
 0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1

In [22]:
def compare_labels(predicted_labels, actual_labels):
    """ a more neatly formatted comparison """
    NUM_LABELS = len(predicted_labels)
    num_correct = 0
    
    for i in range(NUM_LABELS):
        p = int(round(predicted_labels[i]))         # round protects from fp error 
        a = int(round(actual_labels[i]))
        result = "incorrect"
        if p == a:  # if they match,
            result = ""       # no longer incorrect
            num_correct += 1  # and we count a match!

        print(f"row {i:>3d} : {p}  {a}   {result}")   

    print()
    print("Correct:", num_correct, "out of", NUM_LABELS)
    return num_correct

# let's try it out!
compare_labels(predicted_labels,actual_labels)

row   0 : 0  0   
row   1 : 0  0   
row   2 : 0  0   
row   3 : 0  1   incorrect
row   4 : 0  0   
row   5 : 0  1   incorrect
row   6 : 0  1   incorrect
row   7 : 1  0   incorrect
row   8 : 0  0   
row   9 : 0  0   
row  10 : 0  0   
row  11 : 0  1   incorrect
row  12 : 0  1   incorrect
row  13 : 0  1   incorrect
row  14 : 0  0   
row  15 : 0  0   
row  16 : 0  0   
row  17 : 0  0   
row  18 : 0  1   incorrect
row  19 : 0  1   incorrect
row  20 : 0  0   
row  21 : 0  0   
row  22 : 0  1   incorrect
row  23 : 0  1   incorrect
row  24 : 0  0   
row  25 : 0  1   incorrect
row  26 : 0  0   
row  27 : 0  0   
row  28 : 0  0   
row  29 : 0  0   
row  30 : 0  0   
row  31 : 0  0   
row  32 : 0  1   incorrect
row  33 : 0  0   
row  34 : 0  1   incorrect
row  35 : 0  1   incorrect
row  36 : 1  0   incorrect
row  37 : 0  1   incorrect
row  38 : 0  0   
row  39 : 0  1   incorrect
row  40 : 0  1   incorrect
row  41 : 0  0   
row  42 : 0  1   incorrect
row  43 : 0  0   
row  44 : 1  1   
row  45 : 

116

In [24]:
def predictive_model( Features ):
    """ input: a list of four features 
                [ sepallen, sepalwid, petallen, petalwid ]
        output: the predicted species of iris, from
                  setosa (0), versicolor (1), virginica (2)
    """
    our_features = np.asarray([Features])                 # extra brackets needed
    predicted_species = knn_model.predict(our_features)
    
    predicted_species = int(round(predicted_species[0]))  # unpack one element
    return predicted_species
    
#
Features = [2, 4.2, 0, 0, 1]  # [5.8,2.7,4.1,1.0] [4.6,3.6,3.0,2.2] [6.7,3.3,5.7,2.1]
result = predictive_model( Features )
print(f"I predict {result} from Features {Features}")

I predict 1 from Features [2, 4.2, 0, 0, 1]


In [26]:
from sklearn.model_selection import cross_val_score



best_k = 84  # Not correct!
best_accuracy = 0.0  # also not correct...

# Note that we are cross-validating using only our TEST data!
for k in range(1,85):
    knn_cv_model = KNeighborsClassifier(n_neighbors=k)   # build knn_model for every k!
    cv_scores = cross_val_score( knn_cv_model, X_train, y_train, cv=5 )  # cv=5 means 80/20
    print(cv_scores)  # just to see the five scores... 
    average_cv_accuracy = cv_scores.mean()  # mean() is numpy's built-in average function 
    print(f"k: {k:2d}  cv accuracy: {average_cv_accuracy:7.4f}")

    
# assign best value of k to best_k
    if average_cv_accuracy > best_accuracy:
        best_accuracy = average_cv_accuracy
        best_k = k      # at the moment this is incorrect   TO DO for hw4pr1: fix this...
# you'll need to use the loop above to find and remember the real best_k

print(f"best_k = {best_k}   yields the highest average cv accuracy.")  # print the best one



[0.68322981 0.70186335 0.68322981 0.70186335 0.67295597]
k:  1  cv accuracy:  0.6886
[0.71428571 0.69565217 0.68944099 0.72670807 0.67295597]
k:  2  cv accuracy:  0.6998
[0.77018634 0.72049689 0.72049689 0.75776398 0.71069182]
k:  3  cv accuracy:  0.7359
[0.73913043 0.70186335 0.69565217 0.72049689 0.71698113]
k:  4  cv accuracy:  0.7148
[0.79503106 0.74534161 0.72049689 0.74534161 0.72327044]
k:  5  cv accuracy:  0.7459
[0.7515528  0.71428571 0.70186335 0.73913043 0.72327044]
k:  6  cv accuracy:  0.7260
[0.80745342 0.74534161 0.71428571 0.73913043 0.72955975]
k:  7  cv accuracy:  0.7472
[0.79503106 0.72049689 0.72049689 0.72049689 0.73584906]
k:  8  cv accuracy:  0.7385
[0.80124224 0.7515528  0.73291925 0.72670807 0.74213836]
k:  9  cv accuracy:  0.7509
[0.78881988 0.72670807 0.70807453 0.70807453 0.72327044]
k: 10  cv accuracy:  0.7310
[0.78881988 0.74534161 0.70807453 0.73291925 0.74842767]
k: 11  cv accuracy:  0.7447
[0.77639752 0.72049689 0.69565217 0.73913043 0.72955975]
k: 12  c

In [27]:
best_k = 9
from sklearn.neighbors import KNeighborsClassifier
knn_model_tuned = KNeighborsClassifier(n_neighbors=best_k)   # here, we use the best_k!

# we train the model (one line!)
knn_model_tuned.fit(X_train, y_train)                              # yay!  trained!
print(f"Created + trained a knn classifier, now tuned with a (best) k of {best_k}")  

# How does it do?!  The next cell will show...

Created + trained a knn classifier, now tuned with a (best) k of 9


In [28]:
predicted_labels = knn_model_tuned.predict(X_test)
actual_labels = y_test

# Let's print them so we can compare...
print("Predicted labels:", predicted_labels)
print("Actual labels:", actual_labels)

# And, the overall results
num_correct = sum(predicted_labels == actual_labels)
total = len(actual_labels)
print(f"\nResults on test set:  {num_correct} correct out of {total} total.\n\n")

# Plus, we'll print our nicer table...
compare_labels(predicted_labels,actual_labels)

Predicted labels: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1.
 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1.
 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0.
 0. 0. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 1. 0.
 1. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 1. 0.]
Actual labels: [0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1.
 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 0. 1.
 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1.
 1. 0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0.
 0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0

142